### PR TITLE
Add `urlPrefix` to sentry configuration

### PR DESCRIPTION
**Pull request by denrase**
## :scroll: Description

Add `urlPrefix` to sentry configuration

## :bulb: Motivation and Context

Continuation of #222

## :green_heart: How did you test it?

Unit tests

## :pencil: Checklist

- [x] I reviewed submitted code
- [x] I added tests to verify changes
- [x] I updated the docs if needed
- [x] All tests passing
- [x] No breaking changes

### CODE REVIEW

**Comment by denrase** [comment]
@buenaflor Building upon the work of [JoydS](https://github.com/JoydS) so we can merge this.

**Review by buenaflor — APPROVED** [review]

**Comment by JoydS** [comment]
Im sorry but there is a mistake in the documentation

**Comment by denrase** [comment]
@JoydS Could you point me to the incorrect documentation?

**Comment by JoydS** [comment]
The example

**Comment by denrase** [comment]
Sorry for not being more clear, I meant what **specifically** is wrong in the example?

**Comment by JoydS** [comment]
It should be "~/app/"m not "https://mysentry.invalid/"

**Comment by denrase** [comment]
@JoydS Ah yes 🤦 Fixed in #254

**Comment by lukaszmielczarekdev** [comment]
Can we make a release with this feature?

**Comment by JoydS** [comment]
It supposes to be realised but it's not working, I don't know why. Everything is still minified on my side.

**Comment by lukaszmielczarekdev** [comment]
In my opinion it is not, please look at the last release date.

**Comment by buenaflor** [comment]
hey we will make a release on Monday that will include this

**Comment by lukaszmielczarekdev** [comment]
Thanks a lot. But it is not working for me, everything is still minified. Can anyone confirm that it works for them?

**Comment by lukaszmielczarekdev** [comment]
> @lukaszmielczarekdev did you follow the guide in the readme regarding also updating your beforeSend?

Yeah 😉

**Comment by lukaszmielczarekdev** [comment]
The problem I have is that it doesn't send .dart files to Sentry, it only sends one package with .js files (10 pieces). There should be a second portion, much larger with .dart files. The logs say that it found 10 files first, then 0. In the previous version of the package, all files were sent, and in the latest one only one part.

config

Version 2.2.0
part

Version 2.1.0 (prefix added)
all

**Comment by buenaflor** [comment]
thanks for the info @lukaszmielczarekdev do you mind creating an issue here? it's easier for us this way 🙏

**Comment by lukaszmielczarekdev** [comment]
Yeah, sure. Done 😉

**Pull request merged**
