### PR TITLE
feat: sentry.properties

### LINKED ISSUE #42: Support sentry.properties
Right now the configuration is read thru the plugin configuration or via env. var.
Sentry Wizard is able to generate a properties file, the plugin could read the conf. from this file as well.

### PR DESCRIPTION
**Pull request by buenaflor**
## :scroll: Description

Add sentry.properties for additional config options.

it tries to load `sentry.properties` first and if it doesn't exist it will fallback to `pubspec.yaml`

## :bulb: Motivation and Context

Closes #42 

## :green_heart: How did you test it?
Unit test
Manually

## :pencil: Checklist

- [x] I reviewed submitted code
- [x] I added tests to verify changes
- [ ] I updated the docs if needed
- [x] All tests passing
- [x] No breaking changes

## :crystal_ball: Next steps
Add sentry docs

### CODE REVIEW

**Comment by krystofwoldrich** [comment]
I don't have any comment on the code, that looks good to me.

I'm a bit concerned if this is not a breaking feature given the order we read the configs. If `sentry.properties` in the root of a Flutter project has not been used for anything till now, it should be fine.

I think the safer order would be to try first `pubspec.yaml` then `sentry.properties` then `env`. Although a bit more complex I would expect these two configs can coexist. 

That would allow users to hide sensitive config to the properties file and then not commit it for example. Maybe not necessary.

**Comment by buenaflor** [comment]
@krystofwoldrich it seems like sentry.properties on the gradle plugin only uses org, project and auth-token so I think using `sentry.properties` as fallback and separating is the way to go. I guess we can adjust our approach based on demand but I think it should be good enough for now

**Comment by jtmuller5** [comment]
How are you supposed to create the sentry.properties file? I tried creating it as a json and as list of values like in pubspec.yaml but it is not recognized by the CLI

**Comment by buenaflor** [comment]
```shell
key=value
# e.g
upload_debug_symbols=true
```

we'll add docs to the readme for that

- [ ] Add docs for `sentry.properties`

**Pull request merged**
